### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by aHunsader** [CS130-W20/team-A9#12]
## User Story
As a user, I would like to create an account so that I can use the webapp's services.

## Detailed Description
account type, username, password, full name, e-mail (optional), phone number (optional)

## Acceptance Criteria
- [ ] Given I want to use the webapp HomeYess, then I can create an account as a company, homeless person, or volunteer

**Comment by quentintruong** [comment]
account type, username, password, full name, email, and phone are done. 
we cannot yet distinguish between company, homeless, and volunteer
