### ISSUE TITLE
View job board

### ISSUE THREAD

**Issue by quentintruong** [CS130-W20/team-A9#4]
## User Story
As a homeless person, I would like to view a job board so that I can find jobs.

## Detailed Description
A homeless person can view the list of posted jobs and click on a job to see more information.
## Acceptance Criteria
- [x] Given that I'm a homeless person, then I can select a job.

**Comment by lexiekemp** [comment]
> ## User Story
> As a homeless person, I would like to view a job board so that I can find jobs.
> 
> ## Detailed Description
> A homeless person can view the list of posted jobs and click on a link to apply on the company's website.
> 
> ## Acceptance Criteria
> * [ ]  Given **[Condition]**, then **[Expected Result]**
> * [ ]  Given **[Condition]**, then **[Expected Result]**
> * [ ]  Given **[Condition]**, then **[Expected Result]**

**Comment by lexiekemp** [comment]
Created a job board page that lists all jobs posted
